Repository kubesphere-sigs/ks, pull requests merged in 2021-12, with the labels that each got.

#245 Migrate SonarQube configuration from kubesphere-config into devops-config
  go.mod
  kubectl-plugin/config/migrate.go
  kubectl-plugin/config/migrate_test.go
Labels: enhancement, approved, size/L, lgtm

#247 Add tekton manifests for pull request
  .github/tekton/README.md
  .github/tekton/build-bot.yaml
  .github/tekton/git-clone.yaml
  .github/tekton/github-set-status.yaml
  .github/tekton/goreleaser.yaml
  .github/tekton/pull-request.yaml
  .github/tekton/shared-storage.yaml
  .github/tekton/trigger-eventlistener.yaml
  .github/tekton/trigger-rbac.yaml
  .github/workflows/pull-request.yaml.disable
Labels: approved, size/XL, lgtm

#248 Add gateway and ingress manifests
  .github/tekton/README.md
  .github/tekton/gateway.yaml
  .github/tekton/ingress.yaml
  .github/tekton/trigger-eventlistener.yaml
Labels: approved, size/M, lgtm

#249 Typo fix dashboard-url
  .github/tekton/trigger-eventlistener.yaml
Labels: size/XS, approved, lgtm, tide/merge-method-squash

#250 Fix typo of build-bot
  .github/tekton/trigger-eventlistener.yaml
Labels: size/XS, approved, lgtm

#251 Simplify Tekton manifests
  .github/tekton/README.md
  .github/tekton/build-bot.yaml
  .github/tekton/gateway.yaml
  .github/tekton/git-clone.yaml
  .github/tekton/github-set-status.yaml
  .github/tekton/goreleaser.yaml
  .github/tekton/ingress.yaml
  .github/tekton/pull-request-pipeline.yaml
  .github/tekton/pull-request-trigger-template.yaml
  .github/tekton/pull-request-trigger.yaml
  .github/tekton/trigger-eventlistener.yaml
  .github/tekton/trigger-rbac.yaml
Labels: approved, size/XL, lgtm

#254 Support to create Pipeline on the k8s instead of the KubeSphere
  go.mod
  go.sum
  kubectl-plugin/pipeline/dashboard.go
  kubectl-plugin/pipeline/option/create.go
  kubectl-plugin/pipeline/ui/project/form.go
Labels: approved, size/M, lgtm, tide/merge-method-squash
