Repository kubesphere-sigs/ks, pull requests merged in 2021-09, with the labels that each got.

#187 Make PipelineRun support parameterized trigger
  kubectl-plugin/pipeline/run.go
  kubectl-plugin/pipeline/run_test.go
Labels: enhancement

#191 Support to create workspacetemplate automatically
  kubectl-plugin/pipeline/create.go
Labels: enhancement

#190 Add support install required and optional tools
  go.mod
  go.sum
  kubectl-plugin/entrypoint/cmd.go
Labels: enhancement

#200 Avoid overwride configs of container for docker mode
  kubectl-plugin/install/kk.go
Labels: enhancement

#199 Bump the default k3s version from to rancher/k3s:v1.19.14-k3s1
  kubectl-plugin/install/k3d.go
Labels: chore

#121 Print more cluster info when setting multi-cluster
  kubectl-plugin/common/installer.go
  kubectl-plugin/config/cluster.go
Labels: enhancement, approved, size/M

#203 Change the version of PipelineRun to v1alpha3
  kubectl-plugin/pipeline/run.go
  kubectl-plugin/types/schema.go
Labels: chore

#207 Add flag completion for ks install command
  kubectl-plugin/install/installer.go
  kubectl-plugin/install/k3d.go
  kubectl-plugin/install/kind.go
  kubectl-plugin/install/kk.go
Labels: enhancement

#212 Remove the homebrew part due to this is not belong to linuxsuren
  .goreleaser.yml
Labels: chore

#210 Set a name for k3d nightly
  kubectl-plugin/install/k3d.go
  kubectl-plugin/install/kind.go
  kubectl-plugin/install/kk.go
Labels: enhancement

#211 Support to create a parallel pipeline
  kubectl-plugin/pipeline/create.go
  kubectl-plugin/pipeline/tpl/parallel.groovy
  kubectl-plugin/pipeline/tpl/resource.go
  kubectl-plugin/pipeline/tpl/resource_test.go
Labels: enhancement

#213 Add a dashboard for pipelines
  go.mod
  go.sum
  kubectl-plugin/common/client.go
  kubectl-plugin/pipeline/dashboard.go
  kubectl-plugin/pipeline/root.go
  kubectl-plugin/pipeline/run.go
Labels: enhancement

#217 Support create a pipline on the dashboard page
  kubectl-plugin/pipeline/create.go
  kubectl-plugin/pipeline/dashboard.go
  kubectl-plugin/pipeline/ui/stack.go
Labels: enhancement

#219 Add pipline gc condition support
  kubectl-plugin/pipeline/gc.go
  kubectl-plugin/pipeline/gc_test.go
Labels: enhancement

#218 Add support show the pipeline and pipelinerun as YAML format
  kubectl-plugin/pipeline/dashboard.go
Labels: enhancement
